### ISSUE TITLE
No longer works with v24

### ISSUE THREAD

**Issue by EXCIDIVM** [scruffynerf/StashNfoExporterKodi#11]
Hello.
Greatest Plugin EVER made.
Unfortunately, with v24 it seems it stopped working. Didn't change the configuration of the plugin I had with v23, since SNEK doesn't show up in the plugin manager.

**Comment by MRobi1** [comment]
Most plugins need to be reconfigured to be compatible with v24. Hopefully this one isn't dead.

**Comment by robertoleonardo** [comment]
+1 for hoping this isn't dead...

**Comment by noxvia** [comment]
+1... just found and hoping that i can use it

**Comment by rustyinfinity** [comment]
I wrote a plugin for it https://github.com/rustyinfinity/StashNfoExporter . There can be issues and some missing features so pls report if you are using and face any i will fix them .

**Comment by EXCIDIVM** [comment]
> I wrote a plugin for it https://github.com/rustyinfinity/StashNfoExporter . There can be issues and some missing features so pls report if you are using and face any i will fix them .

Thanks, that's a good start. Unfortunately, it does not create the .strm files and it doesn't allow me to save the nfo/strm files in a central directory.
But for now, it's what will use. So your efforts are much appreciated.

**Comment by masterr2001** [comment]
Just wanted to let you know, that I fixed my fork (which should just work like this Plugin, but adds some more options)
You find it here https://github.com/masterr2001/StashNfoExporterKodi

**Comment by EXCIDIVM** [comment]
> Just wanted to let you know, that I fixed my fork (which should just work like this Plugin, but adds some more options) You find it here https://github.com/masterr2001/StashNfoExporterKodi

Thank you so much! Unfortunately, it doesn't work for me.

File "/root/.stash/plugins/StashNfoExporterKodi/make_nfo.py", line 7, in <module>
from stash_interface import StashInterface
ModuleNotFoundError: No module named 'stash_interface'
Scene.Update.Post [Stash NFO Exporter for Kodi]: returned error: exit status 1

**Comment by mod242** [comment]
I am so sorry, I made a mistake, when creating the repo for stash. I just corrected and the module should now be shipped in the package.
Just add the repo https://masterr2001.github.io/StashNfoExporterKodi/index.yml or download the latest source.

**Comment by rtheron** [comment]
> Just wanted to let you know, that I fixed my fork (which should just work like this Plugin, but adds some more options) You find it here https://github.com/masterr2001/StashNfoExporterKodi

@masterr2001 I can't get this to work, I keep getting the following error in the stash log, no matter what I scan/add/update in the library, and no nfo is generated:

24-07-20 04:42:18
Error   
Scene.Create.Post [Stash NFO Exporter for Kodi]: returned error: exit status 1
2024-07-20 04:42:18
Error   
[Plugin / Stash NFO Exporter for Kodi]     import requests, filetype
2024-07-20 04:42:18
Error   
[Plugin / Stash NFO Exporter for Kodi]   File "/root/.stash/plugins/StashNfoExporterKodi/make_nfo.py", line 9, in <module>
2024-07-20 04:42:18
Error   
[Plugin / Stash NFO Exporter for Kodi] Traceback (most recent call last):
2024-07-20 04:42:18
Error   
[Plugin / Stash NFO Exporter for Kodi] ModuleNotFoundError: No module named 'filetype'

**Comment by masterr2001** [comment]
I am so sorry, for getting back so late (was afk for some days)
You need to install the filetype-module for python (either by using the requirements.txt or just by typing `pip install filetype` on your stash host)
